### PR TITLE
Replace code in getting started with asciinema video

### PR DESCRIPTION
**Pull request by da-kami**
Preview with embedded video: https://deploy-preview-17--comit-network.netlify.com/docs/getting-started/create-comit-app/

### CODE REVIEW

**Comment by yosriady** [comment]
Screenshot 2020-02-10 at 11 29 25 AM

The deploy link is always available under the 'Checks' section of your PR: https://deploy-preview-17--comit-network.netlify.com/

**Comment by yosriady** [comment]
I'm not sure if Asciinema can be embedded on Markdown, but you can certainly embed arbitrary HTML elements on Markdown. For example Youtube embeds: 

```
<iframe width="560" height="315" src="https://www.youtube.com/embed/fh-i8lVhN9o" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

**Comment by yosriady** [comment]
Maybe you can also try the iframe approach: https://github.com/asciinema/asciinema-server/pull/286

**Comment by da-kami** [comment]
Unfortunately not stable enough. The embedded player (through script) does not always appear properly. Out of 10 refresh it would only be shown 2~ times. 
Closing this for now, requires more testing.

**Pull request closed without merging**
